### ISSUE TITLE
Text Editor: Write some text and press TAB, the written text also moves with tab.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#971]
If write some text on text editor & press TAB. The written text moves also with tab.

**Text written:**
![Screenshot from 2019-03-29 15-37-53](https://user-images.githubusercontent.com/36185596/55225470-b16f0500-5238-11e9-9bbb-be8ff3a944b3.png)

**After press TAB:**
![Screenshot from 2019-03-29 15-38-08](https://user-images.githubusercontent.com/36185596/55225489-bd5ac700-5238-11e9-93e0-23312c158bad.png)

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps
![te tab](https://user-images.githubusercontent.com/38027574/62917019-4aea1e00-bdb8-11e9-8a6f-d5f1c565cd90.PNG)

**Comment by bogatisuman** [comment]
We made our editor using FirePad which is originally made from Code mirror. 

The same behaviour above mentioned  is happening on FirePad [Rich Text Editor ](https://firepad.io/examples/#richtext-fnw4iQj0UE). 

We can disabled the tab completely but that we don't want, because we want the tab space if user's cursor is ahead of word.
